source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '>= 3.0.0'

# CocoaPods for managing iOS dependencies
gem 'cocoapods', '~> 1.15'

# Required for CocoaPods
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
